[build]
  publish = "build"
  command = "yarn build"

#[[redirects]]
#  from = "https://bless-tools.netlify.com/*"
#  to = "https://tools.blesswinsamuel.com/:splat"
#  status = 301
#  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

